name: belajar_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+21
  flutter_screenutil: ^4.0.2+2
  table_calendar: ^2.3.3
  camera: ^0.7.0+2
  image_cropper: ^1.3.1
  flutter_cached_pdfview: ^0.3.5
  flutter_html: ^1.2.0
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  dio: ^3.0.10
  connectivity: ^2.0.2
  path_provider: ^1.6.27
  path: ^1.7.0
  open_file: ^3.0.3
  flushbar: ^1.10.4
  easy_localization: ^2.3.3
  provider: ^4.3.3
  permission_handler: ^5.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
    